# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08499f270f1d890ef269a4dfbd015eeb255092250c96511915c0ea9e4c57ee159dbcd56e680f3e4d61189fed8d4ef9d5ecf907620b3910119879d8b1f6fb8c40

test:
  secret_key_base: cbe58e3518b7be3e1de9a2d972c99c8b2cb9091a8243fe527e5a880733b65a8855c43b996acc57959724d16edbbf49d93b0c971f8028f21a6c3cda0319ffb712

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
